module.exports = {
  rules: {
    //  Core rules:
    'node/callback-return': 'off',
    'node/exports-style': 'off',
    'node/file-extension-in-import': 'off',
    'node/global-require': 'off',
    'node/handle-callback-err': 'off',
    'node/no-callback-literal': 'off',
    'node/no-deprecated-api': 'off',
    'node/no-exports-assign': 'off',
    'node/no-extraneous-import': 'off',
    'node/no-extraneous-require': 'off',
    'node/no-hide-core-modules': 'off',
    'node/no-missing-import': 'off',
    'node/no-missing-require': 'off',
    'node/no-mixed-requires': 'off',
    'node/no-new-require': 'off',
    'node/no-path-concat': 'off',
    'node/no-process-env': 'off',
    'node/no-process-exit': 'off',
    'node/no-restricted-import': 'off',
    'node/no-restricted-require': 'off',
    'node/no-sync': 'off',
    'node/no-unpublished-bin': 'off',
    'node/no-unpublished-import': 'off',
    'node/no-unpublished-require': 'off',
    'node/no-unsupported-features': 'off',
    'node/process-exit-as-throw': 'off',
    'node/shebang': 'off',
    //  No unsupported features:
    'node/no-unsupported-features/es-builtins': 'off',
    'node/no-unsupported-features/es-syntax': 'off',
    'node/no-unsupported-features/node-builtins': 'off',
    //  Prefer global:
    'node/prefer-global/buffer': 'off',
    'node/prefer-global/console': 'off',
    'node/prefer-global/process': 'off',
    'node/prefer-global/text-decoder': 'off',
    'node/prefer-global/text-encoder': 'off',
    'node/prefer-global/url-search-params': 'off',
    'node/prefer-global/url': 'off',
    //  Prefer promises:
    'node/prefer-promises/dns': 'off',
    'node/prefer-promises/fs': 'off',
  },
};
