module.exports = {
  rules: {
    'import/default': 0,
    'import/dynamic-import-chunkname': 0,
    'import/export': 0,
    'import/extensions': 0,
    'import/imports-first': 0,
    'import/named': 0,
    'import/namespace': 0,
    'import/newline-after-import': 0,
    'import/no-amd': 0,
    'import/no-commonjs': 0,
    'import/no-cycle': 0,
    'import/no-deprecated': 0,
    'import/no-duplicates': 0,
    'import/no-extraneous-dependencies': 0,
    'import/no-import-module-exports': 0,
    'import/no-mutable-exports': 0,
    'import/no-named-as-default': 0,
    'import/no-named-as-default-member': 0,
    'import/no-named-export': 0,
    'import/no-namespace': 0,
    'import/no-nodejs-modules': 0,
    'import/no-relative-packages': 0,
    'import/no-relative-parent-imports': 0,
    'import/no-restricted-paths': 0,
    'import/no-unresolved': 0,
    'import/no-unused-modules': 0,
    'import/order': 0,
    'import/prefer-default-export': 0,
  },
};
