module.exports = {
  plugins: ['svelte'],
  rules: {
    //  Extension rules
    'no-inner-declarations': 0,
    'svelte/block-lang': ['error', {
      enforceScriptPresent: false,
      enforceStylePresent: false,
      script: ['ts', null],
      style: 'less',
    }],
    'svelte/button-has-type': 'error',
    //  System
    'svelte/comment-directive': 'error',
    'svelte/derived-has-same-inputs-outputs': 'error',
    //  Experimental
    'svelte/experimental-require-slot-types': 0,
    'svelte/experimental-require-strict-events': 0,
    'svelte/first-attribute-linebreak': 'error',
    'svelte/html-closing-bracket-spacing': 'error',
    'svelte/html-quotes': 'error',
    'svelte/html-self-closing': 'error',
    'svelte/indent': 'error',
    'svelte/infinite-reactive-loop': 'error',
    'svelte/max-attributes-per-line': ['error', {
      'multiline': 1,
      'singleline': 3,
    }],
    'svelte/mustache-spacing': 'error',
    'svelte/no-at-debug-tags': 'error',
    'svelte/no-at-html-tags': 'error',
    'svelte/no-dom-manipulating': 'error',
    'svelte/no-dupe-else-if-blocks': 'error',
    'svelte/no-dupe-on-directives': 'error',
    'svelte/no-dupe-style-properties': 'error',
    'svelte/no-dupe-use-directives': 'error',
    'svelte/no-dynamic-slot-name': 'error',
    'svelte/no-export-load-in-svelte-module-in-kit-pages': 'error',
    'svelte/no-extra-reactive-curlies': 'error',
    'svelte/no-ignored-unsubscribe': 'error',
    'svelte/no-inline-styles': ['error', {
      allowTransitions: true,
    }],
    'svelte/no-immutable-reactive-statements': 'error',
    'svelte/no-inner-declarations': 'error',
    'svelte/no-not-function-handler': 'error',
    'svelte/no-object-in-text-mustaches': 'error',
    'svelte/no-reactive-functions': 'error',
    'svelte/no-reactive-literals': 'error',
    'svelte/no-reactive-reassign': 'error',
    'svelte/no-restricted-html-elements': 'off',
    'svelte/no-shorthand-style-property-overrides': 'error',
    'svelte/no-spaces-around-equal-signs-in-attribute': 'error',
    'svelte/no-store-async': 'error',
    'svelte/no-target-blank': 'error',
    'no-trailing-spaces': 'off',
    'svelte/no-trailing-spaces': 'error',
    'svelte/no-unknown-style-directive-property': 'error',
    'svelte/no-unused-class-name': 'error',
    'svelte/no-unused-svelte-ignore': 'error',
    'svelte/no-useless-mustaches': 'error',
    'svelte/prefer-class-directive': 'error',
    'svelte/prefer-destructured-store-props': 'error',
    'svelte/prefer-style-directive': 'error',
    'svelte/require-each-key': 'error',
    'svelte/require-event-dispatcher-types': 'error',
    'svelte/require-optimized-style-attribute': 'error',
    'svelte/require-store-callbacks-use-set-param': 'error',
    'svelte/require-store-reactive-access': 'error',
    'svelte/require-stores-init': 'warn',
    'svelte/shorthand-attribute': 'error',
    'svelte/shorthand-directive': 'error',
    'svelte/sort-attributes': 'error',
    'svelte/spaced-html-comment': 'error',
    'svelte/system': 'error',
    'svelte/valid-compile': 'error',
    'svelte/valid-each-key': 'error',
    'svelte/valid-prop-names-in-kit-pages': 'error',
  },
};
