module.exports = {
  parserOptions: {
    ecmaVersion: 5,
    sourceType: 'script',
    ecmaFeatures: {},
  },
  env: {},
  globals: {},
  'extends': [
    '../rules/eslint/best-practices/off.js',
    '../rules/eslint/errors/off.js',
    '../rules/eslint/es6/off.js',
    '../rules/eslint/node/off.js',
    '../rules/eslint/strict/off.js',
    '../rules/eslint/style/off.js',
    '../rules/eslint/variables/off.js',
    '../rules/filenames/off.js',
    '../rules/import/off.js',
    '../rules/jest/off.js',
    '../rules/jsx-a11y/off.js',
    '../rules/node/off.js',
    '../rules/promise/off.js',
    '../rules/react/off.js',
    '../rules/react-hooks/off.js',
    '../rules/unicorn/off.js',
  ],
  rules: {},
};
