module.exports = {
  parserOptions: {
    ecmaVersion: 5,
    sourceType: 'script',
    ecmaFeatures: {},
  },
  env: {},
  globals: {},
  'extends': [
    'himynameisdave/rules/eslint/best-practices/off.js',
    'himynameisdave/rules/eslint/errors/off.js',
    'himynameisdave/rules/eslint/es6/off.js',
    'himynameisdave/rules/eslint/node/off.js',
    'himynameisdave/rules/eslint/strict/off.js',
    'himynameisdave/rules/eslint/style/off.js',
    'himynameisdave/rules/eslint/variables/off.js',
    'himynameisdave/rules/filenames/off.js',
    'himynameisdave/rules/import/off.js',
    'himynameisdave/rules/jest/off.js',
    'himynameisdave/rules/promise/off.js',
    'himynameisdave/rules/react/off.js',
    'himynameisdave/rules/react-hooks/off.js',
    'himynameisdave/rules/unicorn/off.js',
  ],
  rules: {},
};
