module.exports = {
  rules: {
    'unicorn/catch-error-name': 'off',
    // 'unicorn/consistent-function-scoping': 'off',
    'unicorn/custom-error-definition': 'off',
    'unicorn/error-message': 'off',
    'unicorn/escape-case': 'off',
    // 'unicorn/expiring-todo-comments': 'off',
    'unicorn/explicit-length-check': 'off',
    'unicorn/filename-case': 'off',
    'unicorn/import-index': 'off',
    'unicorn/new-for-builtins': 'off',
    'unicorn/no-abusive-eslint-disable': 'off',
    'unicorn/no-array-instanceof': 'off',
    'unicorn/no-console-spaces': 'off',
    'unicorn/no-fn-reference-in-iterator': 'off',
    'unicorn/no-for-loop': 'off',
    'unicorn/no-hex-escape': 'off',
    'unicorn/no-keyword-prefix': 'off',
    'unicorn/no-new-buffer': 'off',
    'unicorn/no-process-exit': 'off',
    'unicorn/no-unreadable-array-destructuring': 'off',
    'unicorn/no-unsafe-regex': 'off',
    'unicorn/no-unused-properties': 'off',
    'unicorn/no-zero-fractions': 'off',
    'unicorn/number-literal-case': 'off',
    'unicorn/prefer-add-event-listener': 'off',
    'unicorn/prefer-event-key': 'off',
    'unicorn/prefer-exponentiation-operator': 'off',
    'unicorn/prefer-flat-map': 'off',
    'unicorn/prefer-includes': 'off',
    'unicorn/prefer-node-append': 'off',
    'unicorn/prefer-node-remove': 'off',
    'unicorn/prefer-query-selector': 'off',
    'unicorn/prefer-spread': 'off',
    'unicorn/prefer-starts-ends-with': 'off',
    'unicorn/prefer-text-content': 'off',
    'unicorn/prefer-type-error': 'off',
    'unicorn/prevent-abbreviations': 'off',
    'unicorn/regex-shorthand': 'off',
    'unicorn/throw-new-error': 'off',
    'unicorn/consistent-function-scoping': 'off',
    'unicorn/expiring-todo-comments': 'off',
    'unicorn/no-nested-ternary': 'off',
    'unicorn/prefer-dataset': 'off',
    'unicorn/prefer-reflect-apply': 'off',
    'unicorn/prefer-string-slice': 'off',
  },
};
